-- aight first  up is Phase 1 Reviews CMS schema for PostgreSQL / Supabase.
-- Review  file in Supabase SQL Editor before running it manually.
-- It creates one new table and index; it does not alter or delete existing data.

BEGIN;

CREATE TABLE public.reviews (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(120) NOT NULL,
    quote TEXT NOT NULL,
    client_image_url TEXT NULL,
    rating INTEGER NULL,
    client_type VARCHAR(80) NULL,
    display_order INTEGER NOT NULL DEFAULT 0,
    is_published BOOLEAN NOT NULL DEFAULT FALSE,
    archived_at TIMESTAMP WITHOUT TIME ZONE NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'UTC'),
    CONSTRAINT ck_reviews_rating_range CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
    CONSTRAINT ck_reviews_display_order_nonnegative CHECK (display_order >= 0)
);

CREATE INDEX ix_reviews_public_order
    ON public.reviews (is_published, archived_at, display_order, id);

-- Flask is the access layer. No direct anon/authenticated Supabase Data API
-- policies are created, preventing unpublished or archived rows from being
-- read by bypassing the Flask public endpoints.
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

COMMIT;

-- Future multi-client migration path (do not run now):
-- 1. Create a sites table.
-- 2. Add reviews.site_id as nullable and backfill existing reviews.
-- 3. Add the foreign key and index, then make site_id required after assignment.
